services:
 app:
   build: 
     context: ../../backend/
     dockerfile: Dockerfile
   volumes:
     - ./app.env:/app/app.env
     - ../../backend:/app/src 


   ports:
     - "8080:8080"
   depends_on:
     - postgres
     - redis
     - elasticsearch

 postgres:
   image: postgres:15
   environment:
     - POSTGRES_USER=jobboard
     - POSTGRES_PASSWORD=jobboard
     - POSTGRES_DB=jobboard
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data

 redis:
   image: redis:7
   ports:
     - "6379:6379"
   volumes:
     - redis_data:/data

 elasticsearch:
   image: elasticsearch:8.12.0
   environment:
     - discovery.type=single-node
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - xpack.security.enabled=false
   ports:
     - "9201:9201"
   volumes:
     - elasticsearch_data:/usr/share/elasticsearch/data



volumes:
 postgres_data:
 redis_data:
 elasticsearch_data: